### ISSUE TITLE
generate_message_id() collisions

### ISSUE THREAD

**Issue by guidovranken** [TAXIIProject/libtaxii#117]
generate_message_id() is just a wrapper for a random number generator for numbers 1-100000. As people will start building clients based on libtaxii and taxii-services, collisions are bound to happen and these will lead to errors if a client implementation depends on these ID's to correlate its own messages sent to a service and the subsequent server response identifier by an ID.

It would probably be better to implement this function as part of a class that client implementations are likely to instantiate or derive from, and implement it as a generator of a sequential stream of numbers (i.e., 1, 2, 3, ..), possibly starting at a random offset so as to prevent indications of client uptime and such to be inferred from this stream (security); thereby ensuring each sent message has a unique ID (barring overflows and such, unlikely in the case of Python).

**Comment by guidovranken** [comment]
How about this?

For TAXII 1.0

```python
from uuid import uuid4
message_id = uuid4().int # or str( uuid().int )
```

and for TAXII 1.1

```python
from uuid import uuid4
message_id = str( uuid4() )
```

Granted, although several subsequent random 128 are exceedingly unlikely to collide, randomness will never guarantee uniqueness. However, for now this is a lot more safe than

```python
 94     message_id = random.randint(1, 10 ** maxlen)
 95     return str(message_id)
```

on which basis a collision for two subsequent ID's is bound to happen once in every 10000 generations.

Using a real uuid4 instead of its integer counterpart is not necessary for TAXII 1.1 and the integer version can be used for both versions for now. So my proposed patch is to change

```python
 94     message_id = random.randint(1, 10 ** maxlen)
 95     return str(message_id)
```

into

```python
message_id = uuid.uuid4().int
return str(message_id)
```

Guido

**Comment by traut** [comment]
The issue here might be that some code out there already uses `libtaxii.common.generate_message_id` [method](https://github.com/TAXIIProject/libtaxii/blob/master/libtaxii/common.py#L80) directly. And this method is version-less. I propose we add `version` kwarg to it

**Comment by MarkDavidson** [comment]
I like the `version` kwarg idea. One implementation idea for that is:
```python
def generate_message_id(maxlen=5, version=VID_TAXII_SERVICES_10):
```

I chose TAXII 1.0 as the default because currently the method generates TAXII 1.0 IDs and I think the default behavior should remain as unchanged as possible.

Playing around with `uuid4()`, I think there's something there. However, `uuid4().int` produces numbers that are greater than `sys.maxint` (You'll note that `uuid4().int` produces a variable of type `long`). I'm curious whether this is a concern or not (will people have made assumptions that the returned value is always parseable as an int? Will receiving systems using different libraries break if we start sending message IDs greater than MAXINT?). If it is a concern, I could see using `uuid4().int % sys.maxint` instead of `uuid4().int`

I think for TAXII 1.1, `str( uuid4() )` is reasonable.

If what I've discussed is implemented, the new function would look something like this:
```python
def generate_message_id(maxlen=5, version=VID_TAXII_SERVICES_10):
    if version == VID_TAXII_SERVICES_10:
        return uuid4().int % sys.maxint
    elif version == VID_TAXII_SERVICES_11:
        return str ( uuid4() )
    else:
        raise ValueError('Unknown TAXII Version: %s. Must be a TAXII Services Version ID!', version)
```

Thoughts/comments? If this looks good I can make the change.

Thank you.
-Mark

**Comment by traut** [comment]
does it makes sense to return cast `uuid4().int % sys.maxint` to string as well? like `str(uuid4().int % sys.maxint)`. This will add consistency

**Comment by MarkDavidson** [comment]
@traut,

Yes it does. Good catch!
-Mark

**Comment by traut** [comment]
:+1: from me

**Comment by traut** [comment]
please check my note on 26da55f - https://github.com/TAXIIProject/libtaxii/commit/26da55fabb02dacb423e825b3ba6ad68f78055a3#commitcomment-9761229

**Comment by MarkDavidson** [comment]
I changed in master in https://github.com/TAXIIProject/libtaxii/commit/c717e379ad15f5de2f5adee09db2ec1eb930bf62.

Good catch!
-Mark
