### ISSUE TITLE
poll_client  with specified collection, Error Message: The collection you requested was not found

### ISSUE THREAD

**Issue by I-am-Sherlocked** [TAXIIProject/libtaxii#160]
Trying to use poll_client with a specified data collection, I get the following error
```
Message: The collection you requested was not found
```
The collection does appear using the Yeti UI though, and when querying the DataCollection objects using the django shell. It is also marked as advertised in the Default Collection Management Service.

So I tracked it down to PollService's validate_collection_name method
```
        try:
            collection = self.data_collections.get(name=name)
        except DataCollection.DoesNotExist as dne:
            raise StatusMessageException(in_response_to,
                                         ST_NOT_FOUND,
                                         'The collection you requested was not found',
                                         {SD_ITEM: name})
```
Replacing ```self.data_collections``` with ```DataCollection.objects``` solves the problem with the poll_client query.

**Comment by MarkDavidson** [comment]
@I-am-Sherlocked,

I believe the original code is correct. A Poll Service handles the Data Collections that it is configured to handle, which is why the `self.data_collections` property is accessed. Configuration of a Poll Service's Data Collections can be done in the UI of the Poll Service. The change you mention makes all Poll Services handle all Data Collections (which, if that's your use case, you can certainly do that).

So having a Data Collection available on a Poll Service is a two-step process:

1. Create the Data Collection and Poll Service
2. Configure the Poll Service to permit polling of the Data Collection.

Did I correctly understand your issue?

Thank you.
-Mark
