### ISSUE TITLE
PollService verifying subscriptions

### ISSUE THREAD

**Issue by I-am-Sherlocked** [TAXIIProject/libtaxii#164]
I'm not sure if this is the right place to ask, but why isn't PollService's "requires_subscription" field not enforced anywhere?
When setting the field to true, shouldn't the poll service verify consumer's subscription?

**Comment by MarkDavidson** [comment]
This is the right place to ask, and the short answer is that it just hasn't been implemented it. You are 100% correct with the expected behavior. Partly, the subscription workflows are not well tested and therefore immature, and any code-level tie-in from the Poll Service to a Subscription's state might change as the Subscription concept matures.

One note (and I try to repeat this often) is that asking for these features will help increase their priority/visibility to the TAXII team, so please keep bringing them up! We also gladly accept code contributions.

-Mark

**Comment by MarkDavidson** [comment]
Further discussion on this topic should occur here: https://github.com/TAXIIProject/django-taxii-services/issues/38

**Comment by I-am-Sherlocked** [comment]
OK, thanks Mark.
